export const bx = {
  magicItems: [
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Sword +1',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Sword +1, +2 vs Lycanthropes',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Sword +1, +2 vs. Spell Users',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Sword +1, +3 vs. Undead',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Sword +1, +3 vs. Dragons',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Sword +1, +3 vs. Regenerating Creatures',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Sword +1, +3 vs. Enchanted Monsters',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Sword + 1, casts light on command',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: "30' radius",
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Sword +1, locate objects',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Sword + 1, flames on command',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Sword + 1, drains life energy, 5-8 levels',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes:
        'One level is drained per hit; after 1d4+4 levels have been drained total, the sword becomes simply +1.',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Sword +1, wishes',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Sword +2',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Sword +2, Charm Person',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Sword +3',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Sword -1, cursed',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Sword -2, cursed',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Shield +1',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Shield +2',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Armor +2',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Shield +3',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Armor +3',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Cursed Shield -2',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Cursed Armor -2',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Cursed Armor -1',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Cursed Shield, AC 9',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Cursed Armor, AC 9',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: 'Appears to be Armor +1',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Armor +1',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Arrows +1 (10 arrows)',
      quantity: { modifier: 0, multiplier: 10, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Axe +1',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Dagger +1',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Mace +1',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Ring of Animal Control',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Ring of Fire Resistance',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Ring of Invisibility',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Ring of Protection +1',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Ring of Water Walking',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Ring of Weakness',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Wand of Enemy Detection',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Wand of Magic Detection',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Wand of Paralyzation',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Staff of Healing',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Snake Staff',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Rod of Cancellation',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Potion of Diminution',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Potion of ESP',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Potion of Gaseous Form',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Potion of Growth',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Potion of Healing',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Potion of Invisibility',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Potion of Levitation',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Potion of Poison',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Bag of Devouring',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Bag of Holding',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Broom of Flying',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Crystal Ball',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Elven Cloak & Boots',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Gauntlets of Ogre Power',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Helm of Alignment Changing',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Helm of Telepathy',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Medallion of ESP',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Rope of Climbing',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Spell scroll: 1 magic-user/elf spell*',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes:
        '* There is a 25% chance the scroll will have clerical spells instead.',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Spell scroll: 2 magic-user/elf spell*',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes:
        '* There is a 25% chance the scroll will have clerical spells instead.',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Spell scroll: 3 magic-user/elf spell*',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes:
        '* There is a 25% chance the scroll will have clerical spells instead.',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Cursed scroll',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Scroll of Protection from Lycanthropes',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Scroll of Protection from Undead',
      quantity: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      type: 'Magic Item',
      notes: '',
    },
  ],
  magicItemTables: [
    {
      diceToRoll: { modifier: 0, multiplier: 1, pips: 8, no: 1 },
      name: 'Swords (Basic)',
      system: 'BX',
      entries: [
        {
          chanceOf: { low: 1, high: 1 },
          persistenceType: 'greg-magic-item',
          reference: 'Sword +1',
        },
        {
          chanceOf: { low: 2, high: 2 },
          persistenceType: 'greg-magic-item',
          reference: 'Sword +1, +2 vs Lycanthropes',
        },
        {
          chanceOf: { low: 3, high: 3 },
          persistenceType: 'greg-magic-item',
          reference: 'Sword +1, +2 vs. Spell Users',
        },
        {
          chanceOf: { low: 4, high: 4 },
          persistenceType: 'greg-magic-item',
          reference: 'Sword +1, +3 vs. Undead',
        },
        {
          chanceOf: { low: 5, high: 5 },
          persistenceType: 'greg-magic-item',
          reference: 'Sword +1, +3 vs. Dragons',
        },
        {
          chanceOf: { low: 6, high: 6 },
          persistenceType: 'greg-magic-item',
          reference: 'Sword + 1, casts light on command',
        },
        {
          chanceOf: { low: 7, high: 7 },
          persistenceType: 'greg-magic-item',
          reference: 'Sword +2',
        },
        {
          chanceOf: { low: 8, high: 8 },
          persistenceType: 'greg-magic-item',
          reference: 'Sword -1, cursed',
        },
      ],
    },
    {
      diceToRoll: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Swords (Expert)',
      system: 'BX',
      entries: [
        {
          chanceOf: { low: 1, high: 40 },
          persistenceType: 'greg-magic-item',
          reference: 'Sword +1',
        },
        {
          chanceOf: { low: 41, high: 46 },
          persistenceType: 'greg-magic-item',
          reference: 'Sword +1, +2 vs Lycanthropes',
        },
        {
          chanceOf: { low: 47, high: 52 },
          persistenceType: 'greg-magic-item',
          reference: 'Sword +1, +2 vs. Spell Users',
        },
        {
          chanceOf: { low: 53, high: 57 },
          persistenceType: 'greg-magic-item',
          reference: 'Sword +1, +3 vs. Undead',
        },
        {
          chanceOf: { low: 58, high: 62 },
          persistenceType: 'greg-magic-item',
          reference: 'Sword +1, +3 vs. Dragons',
        },
        {
          chanceOf: { low: 63, high: 67 },
          persistenceType: 'greg-magic-item',
          reference: 'Sword +1, +3 vs. Regenerating Creatures',
        },
        {
          chanceOf: { low: 68, high: 72 },
          persistenceType: 'greg-magic-item',
          reference: 'Sword +1, +3 vs. Enchanted Monsters',
        },
        {
          chanceOf: { low: 73, high: 80 },
          persistenceType: 'greg-magic-item',
          reference: 'Sword + 1, casts light on command',
        },
        {
          chanceOf: { low: 81, high: 83 },
          persistenceType: 'greg-magic-item',
          reference: 'Sword +1, locate objects',
        },
        {
          chanceOf: { low: 84, high: 87 },
          persistenceType: 'greg-magic-item',
          reference: 'Sword + 1, flames on command',
        },
        {
          chanceOf: { low: 88, high: 88 },
          persistenceType: 'greg-magic-item',
          reference: 'Sword + 1, drains life energy, 5-8 levels',
        },
        {
          chanceOf: { low: 89, high: 89 },
          persistenceType: 'greg-magic-item',
          reference: 'Sword +1, wishes',
        },
        {
          chanceOf: { low: 90, high: 92 },
          persistenceType: 'greg-magic-item',
          reference: 'Sword +2',
        },
        {
          chanceOf: { low: 93, high: 94 },
          persistenceType: 'greg-magic-item',
          reference: 'Sword +2, Charm Person',
        },
        {
          chanceOf: { low: 95, high: 96 },
          persistenceType: 'greg-magic-item',
          reference: 'Sword +3',
        },
        {
          chanceOf: { low: 97, high: 98 },
          persistenceType: 'greg-magic-item',
          reference: 'Sword -1, cursed',
        },
        {
          chanceOf: { low: 99, high: 100 },
          persistenceType: 'greg-magic-item',
          reference: 'Sword -2, cursed',
        },
      ],
    },
    {
      diceToRoll: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'Armor (Expert)',
      system: 'BX',
      entries: [
        {
          chanceOf: { low: 1, high: 20 },
          persistenceType: 'greg-magic-item',
          reference: 'Shield +1',
        },
        {
          chanceOf: { low: 21, high: 35 },
          persistenceType: 'greg-magic-item',
          reference: 'Armor +1',
        },
        {
          chanceOf: { low: 36, high: 45 },
          persistenceType: 'greg-magic-item',
          reference: 'Shield +1',
        },
        {
          chanceOf: { low: 36, high: 45 },
          persistenceType: 'greg-magic-item',
          reference: 'Armor +1',
        },
        {
          chanceOf: { low: 46, high: 55 },
          persistenceType: 'greg-magic-item',
          reference: 'Shield +2',
        },
        {
          chanceOf: { low: 56, high: 60 },
          persistenceType: 'greg-magic-item',
          reference: 'Armor +2',
        },
        {
          chanceOf: { low: 61, high: 65 },
          persistenceType: 'greg-magic-item',
          reference: 'Shield +2',
        },
        {
          chanceOf: { low: 61, high: 65 },
          persistenceType: 'greg-magic-item',
          reference: 'Armor +2',
        },
        {
          chanceOf: { low: 66, high: 70 },
          persistenceType: 'greg-magic-item',
          reference: 'Shield +3',
        },
        {
          chanceOf: { low: 71, high: 73 },
          persistenceType: 'greg-magic-item',
          reference: 'Armor +3',
        },
        {
          chanceOf: { low: 74, high: 74 },
          persistenceType: 'greg-magic-item',
          reference: 'Shield +3',
        },
        {
          chanceOf: { low: 74, high: 74 },
          persistenceType: 'greg-magic-item',
          reference: 'Armor +3',
        },
        {
          chanceOf: { low: 75, high: 80 },
          persistenceType: 'greg-magic-item',
          reference: 'Cursed Shield -2',
        },
        {
          chanceOf: { low: 81, high: 82 },
          persistenceType: 'greg-magic-item',
          reference: 'Cursed Armor -2',
        },
        {
          chanceOf: { low: 83, high: 85 },
          persistenceType: 'greg-magic-item',
          reference: 'Cursed Armor -1',
        },
        {
          chanceOf: { low: 86, high: 88 },
          persistenceType: 'greg-magic-item',
          reference: 'Cursed Shield, AC 9',
        },
        {
          chanceOf: { low: 89, high: 90 },
          persistenceType: 'greg-magic-item',
          reference: 'Cursed Armor, AC 9',
        },
        {
          chanceOf: { low: 91, high: 93 },
          persistenceType: 'greg-magic-item',
          reference: 'Armor +2',
        },
        {
          chanceOf: { low: 91, high: 93 },
          persistenceType: 'greg-magic-item',
          reference: 'Shield +1',
        },
        {
          chanceOf: { low: 94, high: 95 },
          persistenceType: 'greg-magic-item',
          reference: 'Armor +1',
        },
        {
          chanceOf: { low: 94, high: 95 },
          persistenceType: 'greg-magic-item',
          reference: 'Shield +2',
        },
        {
          chanceOf: { low: 96, high: 96 },
          persistenceType: 'greg-magic-item',
          reference: 'Armor +1',
        },
        {
          chanceOf: { low: 96, high: 96 },
          persistenceType: 'greg-magic-item',
          reference: 'Shield +3',
        },
        {
          chanceOf: { low: 97, high: 97 },
          persistenceType: 'greg-magic-item',
          reference: 'Armor +3',
        },
        {
          chanceOf: { low: 97, high: 97 },
          persistenceType: 'greg-magic-item',
          reference: 'Shield +1',
        },
        {
          chanceOf: { low: 98, high: 98 },
          persistenceType: 'greg-magic-item',
          reference: 'Armor +3',
        },
        {
          chanceOf: { low: 98, high: 98 },
          persistenceType: 'greg-magic-item',
          reference: 'Shield +2',
        },
        {
          chanceOf: { low: 99, high: 99 },
          persistenceType: 'greg-magic-item',
          reference: 'Armor +2',
        },
        {
          chanceOf: { low: 99, high: 99 },
          persistenceType: 'greg-magic-item',
          reference: 'Shield +3',
        },
        {
          chanceOf: { low: 100, high: 100 },
          persistenceType: 'greg-magic-item',
          reference: 'Cursed Armor -2',
        },
        {
          chanceOf: { low: 100, high: 100 },
          persistenceType: 'greg-magic-item',
          reference: 'Shield +1',
        },
      ],
    },
    {
      diceToRoll: { modifier: 0, multiplier: 1, pips: 8, no: 1 },
      name: 'Weapon / Armor (Basic)',
      system: 'BX',
      entries: [
        {
          chanceOf: { low: 1, high: 1 },
          persistenceType: 'greg-magic-item',
          reference: 'Arrows +1 (10 arrows)',
        },
        {
          chanceOf: { low: 2, high: 2 },
          persistenceType: 'greg-magic-item',
          reference: 'Axe +1',
        },
        {
          chanceOf: { low: 3, high: 3 },
          persistenceType: 'greg-magic-item',
          reference: 'Dagger +1',
        },
        {
          chanceOf: { low: 4, high: 4 },
          persistenceType: 'greg-magic-item',
          reference: 'Mace +1',
        },
        {
          chanceOf: { low: 5, high: 5 },
          persistenceType: 'greg-magic-item',
          reference: 'Armor +1',
        },
        {
          chanceOf: { low: 6, high: 6 },
          persistenceType: 'greg-magic-item',
          reference: 'Shield +1',
        },
        {
          chanceOf: { low: 7, high: 7 },
          persistenceType: 'greg-magic-item',
          reference: 'Armor +1',
        },
        {
          chanceOf: { low: 7, high: 7 },
          persistenceType: 'greg-magic-item',
          reference: 'Shield +1',
        },
        {
          chanceOf: { low: 8, high: 8 },
          persistenceType: 'greg-magic-item',
          reference: 'Cursed Armor, AC 9',
        },
      ],
    },
    {
      diceToRoll: { modifier: 0, multiplier: 1, pips: 6, no: 1 },
      name: 'Ring (Basic)',
      system: 'BX',
      entries: [
        {
          chanceOf: { low: 1, high: 1 },
          persistenceType: 'greg-magic-item',
          reference: 'Ring of Animal Control',
        },
        {
          chanceOf: { low: 2, high: 2 },
          persistenceType: 'greg-magic-item',
          reference: 'Ring of Fire Resistance',
        },
        {
          chanceOf: { low: 3, high: 3 },
          persistenceType: 'greg-magic-item',
          reference: 'Ring of Invisibility',
        },
        {
          chanceOf: { low: 4, high: 4 },
          persistenceType: 'greg-magic-item',
          reference: 'Ring of Protection +1',
        },
        {
          chanceOf: { low: 5, high: 5 },
          persistenceType: 'greg-magic-item',
          reference: 'Ring of Water Walking',
        },
        {
          chanceOf: { low: 6, high: 6 },
          persistenceType: 'greg-magic-item',
          reference: 'Ring of Weakness',
        },
      ],
    },
    {
      diceToRoll: { modifier: 0, multiplier: 1, pips: 6, no: 1 },
      name: 'Wand / Staff / Rod (Basic)',
      system: 'BX',
      entries: [
        {
          chanceOf: { low: 1, high: 1 },
          persistenceType: 'greg-magic-item',
          reference: 'Wand of Enemy Detection',
        },
        {
          chanceOf: { low: 2, high: 2 },
          persistenceType: 'greg-magic-item',
          reference: 'Wand of Magic Detection',
        },
        {
          chanceOf: { low: 3, high: 3 },
          persistenceType: 'greg-magic-item',
          reference: 'Wand of Paralyzation',
        },
        {
          chanceOf: { low: 4, high: 4 },
          persistenceType: 'greg-magic-item',
          reference: 'Staff of Healing',
        },
        {
          chanceOf: { low: 5, high: 5 },
          persistenceType: 'greg-magic-item',
          reference: 'Snake Staff',
        },
        {
          chanceOf: { low: 6, high: 6 },
          persistenceType: 'greg-magic-item',
          reference: 'Rod of Cancellation',
        },
      ],
    },
    {
      diceToRoll: { modifier: 0, multiplier: 1, pips: 8, no: 1 },
      name: 'Potion (Basic)',
      system: 'BX',
      entries: [
        {
          chanceOf: { low: 1, high: 1 },
          persistenceType: 'greg-magic-item',
          reference: 'Potion of Diminution',
        },
        {
          chanceOf: { low: 2, high: 2 },
          persistenceType: 'greg-magic-item',
          reference: 'Potion of ESP',
        },
        {
          chanceOf: { low: 3, high: 3 },
          persistenceType: 'greg-magic-item',
          reference: 'Potion of Gaseous Form',
        },
        {
          chanceOf: { low: 4, high: 4 },
          persistenceType: 'greg-magic-item',
          reference: 'Potion of Growth',
        },
        {
          chanceOf: { low: 5, high: 5 },
          persistenceType: 'greg-magic-item',
          reference: 'Potion of Healing',
        },
        {
          chanceOf: { low: 6, high: 6 },
          persistenceType: 'greg-magic-item',
          reference: 'Potion of Invisibility',
        },
        {
          chanceOf: { low: 7, high: 7 },
          persistenceType: 'greg-magic-item',
          reference: 'Potion of Levitation',
        },
        {
          chanceOf: { low: 8, high: 8 },
          persistenceType: 'greg-magic-item',
          reference: 'Potion of Poison',
        },
      ],
    },
    {
      diceToRoll: { modifier: 0, multiplier: 1, pips: 10, no: 1 },
      name: 'Miscellaneous Magic Item (Basic)',
      system: 'BX',
      entries: [
        {
          chanceOf: { low: 1, high: 1 },
          persistenceType: 'greg-magic-item',
          reference: 'Bag of Devouring',
        },
        {
          chanceOf: { low: 2, high: 2 },
          persistenceType: 'greg-magic-item',
          reference: 'Bag of Holding',
        },
        {
          chanceOf: { low: 3, high: 3 },
          persistenceType: 'greg-magic-item',
          reference: 'Broom of Flying',
        },
        {
          chanceOf: { low: 4, high: 4 },
          persistenceType: 'greg-magic-item',
          reference: 'Crystal Ball',
        },
        {
          chanceOf: { low: 5, high: 5 },
          persistenceType: 'greg-magic-item',
          reference: 'Elven Cloak & Boots',
        },
        {
          chanceOf: { low: 6, high: 6 },
          persistenceType: 'greg-magic-item',
          reference: 'Gauntlets of Ogre Power',
        },
        {
          chanceOf: { low: 7, high: 7 },
          persistenceType: 'greg-magic-item',
          reference: 'Helm of Alignment Changing',
        },
        {
          chanceOf: { low: 8, high: 8 },
          persistenceType: 'greg-magic-item',
          reference: 'Helm of Telepathy',
        },
        {
          chanceOf: { low: 9, high: 9 },
          persistenceType: 'greg-magic-item',
          reference: 'Medallion of ESP',
        },
        {
          chanceOf: { low: 10, high: 10 },
          persistenceType: 'greg-magic-item',
          reference: 'Rope of Climbing',
        },
      ],
    },
    {
      diceToRoll: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'General Magic Items (Basic)',
      system: 'BX',
      entries: [
        {
          chanceOf: { low: 1, high: 20 },
          persistenceType: 'greg-magic-item-table',
          reference: 'Swords (Basic)',
        },
        {
          chanceOf: { low: 21, high: 40 },
          persistenceType: 'greg-magic-item-table',
          reference: 'Weapon / Armor (Basic)',
        },
        {
          chanceOf: { low: 41, high: 65 },
          persistenceType: 'greg-magic-item-table',
          reference: 'Potion (Basic)',
        },
        {
          chanceOf: { low: 66, high: 85 },
          persistenceType: 'greg-magic-item-table',
          reference: 'Scroll (Basic)',
        },
        {
          chanceOf: { low: 86, high: 90 },
          persistenceType: 'greg-magic-item-table',
          reference: 'Ring (Basic)',
        },
        {
          chanceOf: { low: 91, high: 95 },
          persistenceType: 'greg-magic-item-table',
          reference: 'Wand / Staff / Rod (Basic)',
        },
        {
          chanceOf: { low: 96, high: 100 },
          persistenceType: 'greg-magic-item-table',
          reference: 'Miscellaneous Magic Item (Basic)',
        },
      ],
    },
    {
      diceToRoll: { modifier: 0, multiplier: 1, pips: 8, no: 1 },
      name: 'Scroll (Basic)',
      system: 'BX',
      entries: [
        {
          chanceOf: { low: 1, high: 1 },
          persistenceType: 'greg-magic-item',
          reference: 'Spell scroll: 1 magic-user/elf spell*',
        },
        {
          chanceOf: { low: 2, high: 2 },
          persistenceType: 'greg-magic-item',
          reference: 'Spell scroll: 2 magic-user/elf spell*',
        },
        {
          chanceOf: { low: 3, high: 3 },
          persistenceType: 'greg-magic-item',
          reference: 'Spell scroll: 3 magic-user/elf spell*',
        },
        {
          chanceOf: { low: 4, high: 4 },
          persistenceType: 'greg-magic-item',
          reference: 'Cursed scroll',
        },
        {
          chanceOf: { low: 5, high: 5 },
          persistenceType: 'greg-magic-item',
          reference: 'Scroll of Protection from Lycanthropes',
        },
        {
          chanceOf: { low: 6, high: 6 },
          persistenceType: 'greg-magic-item',
          reference: 'Scroll of Protection from Undead',
        },
        {
          chanceOf: { low: 7, high: 7 },
          persistenceType: 'greg-magic-item-table',
          reference: 'Treasure Map (1-4k Gold)',
        },
        {
          chanceOf: { low: 8, high: 8 },
          persistenceType: 'greg-magic-item-table',
          reference: 'Treasure Map (1 Hidden Magic Item)',
        },
      ],
    },
  ],
  magicWeaponPowers: [],
  magicWeaponPowerTables: [],
  monsterEncounterLists: [],
  monsterTypes: [],
  treasureArticles: [],
  treasureMapRefs: [
    {
      chanceOf: 100,
      diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
      name: 'BX-Treasure Map (1-4k Gold)-Gold Pieces',
      quantity: { modifier: 0, multiplier: 1000, pips: 4, no: 1 },
      type: 'SPECIE',
    },
  ],
  treasureMaps: [
    {
      diceToRoll: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      name: 'Treasure Map (1-4k Gold)',
      system: 'BX',
      entries: [
        {
          chanceOf: { low: 1, high: 1 },
          persistenceType: 'greg-treasure-map-ref',
          reference: 'BX-Treasure Map (1-4k Gold)-Gold Pieces',
        },
      ],
    },
    {
      diceToRoll: { modifier: 0, multiplier: 1, pips: 1, no: 1 },
      name: 'Treasure Map (1 Hidden Magic Item)',
      system: 'BX',
      entries: [
        {
          chanceOf: { low: 1, high: 1 },
          persistenceType: 'greg-magic-item-table',
          reference: 'General Magic Items (Basic)',
        },
      ],
    },
  ],
  treasureTypes: [
    {
      type: 'A',
      entries: [
        {
          chanceOf: 25,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Copper',
          quantity: { modifier: 0, multiplier: 1000, pips: 6, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 30,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Silver',
          quantity: { modifier: 0, multiplier: 1000, pips: 6, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 20,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Electrum',
          quantity: { modifier: 0, multiplier: 1000, pips: 4, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 35,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gold',
          quantity: { modifier: 0, multiplier: 1000, pips: 6, no: 2 },
          type: 'SPECIE',
        },
        {
          chanceOf: 25,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Platinum',
          quantity: { modifier: 0, multiplier: 1000, pips: 2, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 50,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gems',
          quantity: { modifier: 0, multiplier: 1, pips: 6, no: 6 },
          type: 'GEMS',
        },
        {
          chanceOf: 50,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Jewelry',
          quantity: { modifier: 0, multiplier: 1, pips: 6, no: 6 },
          type: 'JEWELRY',
        },
      ],
      system: 'BX',
    },
    {
      type: 'B',
      entries: [
        {
          chanceOf: 50,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Copper',
          quantity: { modifier: 0, multiplier: 1000, pips: 8, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 25,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Silver',
          quantity: { modifier: 0, multiplier: 1000, pips: 6, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 25,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Electrum',
          quantity: { modifier: 0, multiplier: 1000, pips: 4, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 25,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gold',
          quantity: { modifier: 0, multiplier: 1000, pips: 3, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 25,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gems',
          quantity: { modifier: 0, multiplier: 1, pips: 6, no: 1 },
          type: 'GEMS',
        },
        {
          chanceOf: 25,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Jewelry',
          quantity: { modifier: 0, multiplier: 1, pips: 6, no: 1 },
          type: 'JEWELRY',
        },
      ],
      system: 'BX',
    },
    {
      type: 'C',
      entries: [
        {
          chanceOf: 20,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Copper',
          quantity: { modifier: 0, multiplier: 1000, pips: 12, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 30,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Silver',
          quantity: { modifier: 0, multiplier: 1000, pips: 4, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 10,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Electrum',
          quantity: { modifier: 0, multiplier: 1000, pips: 4, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 25,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gems',
          quantity: { modifier: 0, multiplier: 1, pips: 4, no: 1 },
          type: 'GEMS',
        },
        {
          chanceOf: 25,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Jewelry',
          quantity: { modifier: 0, multiplier: 1, pips: 4, no: 1 },
          type: 'JEWELRY',
        },
      ],
      system: 'BX',
    },
    {
      type: 'D',
      entries: [
        {
          chanceOf: 10,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Copper',
          quantity: { modifier: 0, multiplier: 1000, pips: 8, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 15,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Silver',
          quantity: { modifier: 0, multiplier: 1000, pips: 12, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 60,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gold',
          quantity: { modifier: 0, multiplier: 1000, pips: 6, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 30,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gems',
          quantity: { modifier: 0, multiplier: 1, pips: 8, no: 1 },
          type: 'GEMS',
        },
        {
          chanceOf: 30,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Jewelry',
          quantity: { modifier: 0, multiplier: 1, pips: 8, no: 1 },
          type: 'JEWELRY',
        },
      ],
      system: 'BX',
    },
    {
      type: 'E',
      entries: [
        {
          chanceOf: 5,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Copper',
          quantity: { modifier: 0, multiplier: 1000, pips: 10, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 30,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Silver',
          quantity: { modifier: 0, multiplier: 1000, pips: 12, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 25,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Electrum',
          quantity: { modifier: 0, multiplier: 1000, pips: 4, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 25,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gold',
          quantity: { modifier: 0, multiplier: 1000, pips: 8, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 10,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gems',
          quantity: { modifier: 0, multiplier: 1, pips: 10, no: 1 },
          type: 'GEMS',
        },
        {
          chanceOf: 10,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Jewelry',
          quantity: { modifier: 0, multiplier: 1, pips: 10, no: 1 },
          type: 'JEWELRY',
        },
      ],
      system: 'BX',
    },
    {
      type: 'F',
      entries: [
        {
          chanceOf: 10,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Silver',
          quantity: { modifier: 0, multiplier: 1000, pips: 10, no: 2 },
          type: 'SPECIE',
        },
        {
          chanceOf: 20,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Electrum',
          quantity: { modifier: 0, multiplier: 1000, pips: 8, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 45,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gold',
          quantity: { modifier: 0, multiplier: 1000, pips: 12, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 30,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Platinum',
          quantity: { modifier: 0, multiplier: 1000, pips: 3, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 20,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gems',
          quantity: { modifier: 0, multiplier: 1, pips: 12, no: 2 },
          type: 'GEMS',
        },
        {
          chanceOf: 10,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Jewelry',
          quantity: { modifier: 0, multiplier: 1, pips: 12, no: 1 },
          type: 'JEWELRY',
        },
      ],
      system: 'BX',
    },
    {
      type: 'G',
      entries: [
        {
          chanceOf: 50,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gold',
          quantity: { modifier: 0, multiplier: 10000, pips: 4, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 50,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Platinum',
          quantity: { modifier: 0, multiplier: 1000, pips: 6, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 25,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gems',
          quantity: { modifier: 0, multiplier: 1, pips: 6, no: 3 },
          type: 'GEMS',
        },
        {
          chanceOf: 25,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Jewelry',
          quantity: { modifier: 0, multiplier: 1, pips: 10, no: 1 },
          type: 'JEWELRY',
        },
      ],
      system: 'BX',
    },
    {
      type: 'H',
      entries: [
        {
          chanceOf: 25,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Copper',
          quantity: { modifier: 0, multiplier: 1000, pips: 8, no: 3 },
          type: 'SPECIE',
        },
        {
          chanceOf: 50,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Silver',
          quantity: { modifier: 0, multiplier: 1000, pips: 100, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 50,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Electrum',
          quantity: { modifier: 0, multiplier: 10000, pips: 4, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 50,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gold',
          quantity: { modifier: 0, multiplier: 10000, pips: 6, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 25,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Platinum',
          quantity: { modifier: 0, multiplier: 1000, pips: 4, no: 5 },
          type: 'SPECIE',
        },
        {
          chanceOf: 50,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gems',
          quantity: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          type: 'GEMS',
        },
        {
          chanceOf: 50,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Jewelry',
          quantity: { modifier: 0, multiplier: 10, pips: 4, no: 1 },
          type: 'JEWELRY',
        },
      ],
      system: 'BX',
    },
    {
      type: 'I',
      entries: [
        {
          chanceOf: 30,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Platinum',
          quantity: { modifier: 0, multiplier: 1000, pips: 8, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 50,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gems',
          quantity: { modifier: 0, multiplier: 1, pips: 6, no: 2 },
          type: 'GEMS',
        },
        {
          chanceOf: 50,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Jewelry',
          quantity: { modifier: 0, multiplier: 1, pips: 6, no: 2 },
          type: 'JEWELRY',
        },
      ],
      system: 'BX',
    },
    {
      type: 'J',
      entries: [
        {
          chanceOf: 25,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Copper',
          quantity: { modifier: 0, multiplier: 1000, pips: 4, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 10,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Silver',
          quantity: { modifier: 0, multiplier: 1000, pips: 3, no: 1 },
          type: 'SPECIE',
        },
      ],
      system: 'BX',
    },
    {
      type: 'K',
      entries: [
        {
          chanceOf: 30,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Silver',
          quantity: { modifier: 0, multiplier: 1000, pips: 6, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 10,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Electrum',
          quantity: { modifier: 0, multiplier: 1000, pips: 2, no: 1 },
          type: 'SPECIE',
        },
      ],
      system: 'BX',
    },
    {
      type: 'L',
      entries: [
        {
          chanceOf: 50,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gems',
          quantity: { modifier: 0, multiplier: 1, pips: 4, no: 1 },
          type: 'GEMS',
        },
      ],
      system: 'BX',
    },
    {
      type: 'M',
      entries: [
        {
          chanceOf: 40,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gold',
          quantity: { modifier: 0, multiplier: 1000, pips: 4, no: 2 },
          type: 'SPECIE',
        },
        {
          chanceOf: 50,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Platinum',
          quantity: { modifier: 0, multiplier: 1000, pips: 6, no: 5 },
          type: 'SPECIE',
        },
        {
          chanceOf: 55,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gems',
          quantity: { modifier: 0, multiplier: 1, pips: 4, no: 5 },
          type: 'GEMS',
        },
        {
          chanceOf: 45,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Jewelry',
          quantity: { modifier: 0, multiplier: 1, pips: 6, no: 2 },
          type: 'JEWELRY',
        },
      ],
      system: 'BX',
    },
    {
      type: 'P',
      entries: [
        {
          chanceOf: 100,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Copper',
          quantity: { modifier: 0, multiplier: 1, pips: 12, no: 3 },
          type: 'SPECIE',
        },
      ],
      system: 'BX',
    },
    {
      type: 'Q',
      entries: [
        {
          chanceOf: 100,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Silver',
          quantity: { modifier: 0, multiplier: 1, pips: 6, no: 3 },
          type: 'SPECIE',
        },
      ],
      system: 'BX',
    },
    {
      type: 'R',
      entries: [
        {
          chanceOf: 100,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Electrum',
          quantity: { modifier: 0, multiplier: 1, pips: 6, no: 2 },
          type: 'SPECIE',
        },
      ],
      system: 'BX',
    },
    {
      type: 'S',
      entries: [
        {
          chanceOf: 100,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gold',
          quantity: { modifier: 0, multiplier: 1, pips: 4, no: 2 },
          type: 'SPECIE',
        },
      ],
      system: 'BX',
    },
    {
      type: 'T',
      entries: [
        {
          chanceOf: 100,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Platinum',
          quantity: { modifier: 0, multiplier: 1, pips: 6, no: 1 },
          type: 'SPECIE',
        },
      ],
      system: 'BX',
    },
    {
      type: 'U',
      entries: [
        {
          chanceOf: 10,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Copper',
          quantity: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 10,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Silver',
          quantity: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 5,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gold',
          quantity: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 5,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gems',
          quantity: { modifier: 0, multiplier: 1, pips: 4, no: 1 },
          type: 'GEMS',
        },
        {
          chanceOf: 5,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Jewelry',
          quantity: { modifier: 0, multiplier: 1, pips: 4, no: 1 },
          type: 'JEWELRY',
        },
      ],
      system: 'BX',
    },
    {
      type: 'Unguarded Treasure - Level 1',
      entries: [
        {
          chanceOf: 100,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Silver',
          quantity: { modifier: 0, multiplier: 100, pips: 6, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 50,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gold',
          quantity: { modifier: 0, multiplier: 10, pips: 6, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 5,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gems',
          quantity: { modifier: 0, multiplier: 1, pips: 6, no: 1 },
          type: 'GEMS',
        },
        {
          chanceOf: 2,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Jewelry',
          quantity: { modifier: 0, multiplier: 1, pips: 6, no: 1 },
          type: 'JEWELRY',
        },
      ],
      system: 'BX',
    },
    {
      type: 'Unguarded Treasure - Level 2-3',
      entries: [
        {
          chanceOf: 100,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Silver',
          quantity: { modifier: 0, multiplier: 100, pips: 12, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 50,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gold',
          quantity: { modifier: 0, multiplier: 100, pips: 6, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 10,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gems',
          quantity: { modifier: 0, multiplier: 1, pips: 6, no: 1 },
          type: 'GEMS',
        },
        {
          chanceOf: 5,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Jewelry',
          quantity: { modifier: 0, multiplier: 1, pips: 6, no: 1 },
          type: 'JEWELRY',
        },
      ],
      system: 'BX',
    },
    {
      type: 'Unguarded Treasure - Level 4-5',
      entries: [
        {
          chanceOf: 100,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Silver',
          quantity: { modifier: 0, multiplier: 1000, pips: 6, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 100,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gold',
          quantity: { modifier: 0, multiplier: 200, pips: 6, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 20,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gems',
          quantity: { modifier: 0, multiplier: 1, pips: 6, no: 1 },
          type: 'GEMS',
        },
        {
          chanceOf: 10,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Jewelry',
          quantity: { modifier: 0, multiplier: 1, pips: 6, no: 1 },
          type: 'JEWELRY',
        },
      ],
      system: 'BX',
    },
    {
      type: 'Unguarded Treasure - Level 6-7',
      entries: [
        {
          chanceOf: 100,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Silver',
          quantity: { modifier: 0, multiplier: 2000, pips: 6, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 50,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gold',
          quantity: { modifier: 0, multiplier: 500, pips: 6, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 30,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gems',
          quantity: { modifier: 0, multiplier: 1, pips: 6, no: 1 },
          type: 'GEMS',
        },
        {
          chanceOf: 15,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Jewelry',
          quantity: { modifier: 0, multiplier: 1, pips: 6, no: 1 },
          type: 'JEWELRY',
        },
      ],
      system: 'BX',
    },
    {
      type: 'Unguarded Treasure - Level 8-9',
      entries: [
        {
          chanceOf: 100,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Silver',
          quantity: { modifier: 0, multiplier: 5000, pips: 6, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 50,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gold',
          quantity: { modifier: 0, multiplier: 1000, pips: 6, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 40,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gems',
          quantity: { modifier: 0, multiplier: 1, pips: 12, no: 1 },
          type: 'GEMS',
        },
        {
          chanceOf: 20,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Jewelry',
          quantity: { modifier: 0, multiplier: 1, pips: 12, no: 1 },
          type: 'JEWELRY',
        },
      ],
      system: 'BX',
    },
    {
      type: 'V',
      entries: [
        {
          chanceOf: 10,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Silver',
          quantity: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 5,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Electrum',
          quantity: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 10,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gold',
          quantity: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 5,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Platinum',
          quantity: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          type: 'SPECIE',
        },
        {
          chanceOf: 10,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Gems',
          quantity: { modifier: 0, multiplier: 1, pips: 4, no: 1 },
          type: 'GEMS',
        },
        {
          chanceOf: 10,
          diceRolled: { modifier: 0, multiplier: 1, pips: 100, no: 1 },
          name: 'Jewelry',
          quantity: { modifier: 0, multiplier: 1, pips: 4, no: 1 },
          type: 'JEWELRY',
        },
      ],
      system: 'BX',
    },
  ],
  treasureLists: [
    {
      diceToRoll: { modifier: 0, multiplier: 1, pips: 6, no: 1 },
      name: 'Unguarded Treasure',
      system: 'BX',
      entries: [
        {
          chanceOf: { low: 1, high: 1 },
          persistenceType: 'greg-treasure-type',
          reference: 'Unguarded Treasure - Level 1',
        },
        {
          chanceOf: { low: 2, high: 3 },
          persistenceType: 'greg-treasure-type',
          reference: 'Unguarded Treasure - Level 2-3',
        },
        {
          chanceOf: { low: 4, high: 5 },
          persistenceType: 'greg-treasure-type',
          reference: 'Unguarded Treasure - Level 4-5',
        },
        {
          chanceOf: { low: 6, high: 7 },
          persistenceType: 'greg-treasure-type',
          reference: 'Unguarded Treasure - Level 6-7',
        },
        {
          chanceOf: { low: 8, high: 9 },
          persistenceType: 'greg-treasure-type',
          reference: 'Unguarded Treasure - Level 8-9',
        },
      ],
    },
  ],
};
